### ISSUE TITLE
Flaws in the Vulkan checks

### ISSUE THREAD

**Issue by SandeMC** [ICantReadYourMind/IVFixer#1]
- vulkaninfo will always run with GPU0 first, meaning that if a laptop defines the iGPU as GPU0 and GPU as GPU1, this tool would only check for GPU0 and return inaccurate results. One way to handle this is to query through all GPU's and assume the higher vulkan version found to be the GPU that'll be used to play the game. Correct me if I missed the logic in the code somewhere, though.
- Not really important as it'll probably return 0 or error anyway, but Vulkan 1.0 returns `Vulkan API Version` rather than `Vulkan Instance Version`. Not sure about VK1.1 or VK1.2.

**Comment by ICantReadYourMind** [comment]
1. fixed
2. vulkan 1.0 isnt supported by dxvk

**Comment by SandeMC** [comment]
for 2, you still want to handle the case to error it out correctly. as i said, it probably returns 0 still though

**Comment by ICantReadYourMind** [comment]
i fixed the "query" since i have igpu and gpu in system and it works fine and no reason to error it out correctly because dxvk shouldnt be installed if vk ver is less than 1.1
